def try_catch():
    # try:
    a = int(input("enter value of a :"))
    b = int(input("enter value for b :"))
    c = a/b
    print(c)

    # except:
    #     print("error : division by zero")

obj = try_catch()